input {
  udp {
    port => 5514
    type => "syslog"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:timestamp} %{GREEDYDATA:log_message}"
      }
    }
    mutate {
      add_field => { "environment" => "SOC-LAB" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "soc-logs-%{+YYYY.MM.dd}"
  }
}
